/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/gradio_client/documentation.py:105: UserWarning: Could not get documentation group for <class 'gradio.mix.Parallel'>: No known documentation group for module 'gradio.mix'
  warnings.warn(f"Could not get documentation group for {cls}: {exc}")
/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/gradio_client/documentation.py:105: UserWarning: Could not get documentation group for <class 'gradio.mix.Series'>: No known documentation group for module 'gradio.mix'
  warnings.warn(f"Could not get documentation group for {cls}: {exc}")
2024-07-03 01:39:52 | INFO | gradio_web_server | args: Namespace(host='0.0.0.0', port=10058, controller_url='http://10.140.24.69:10050', concurrency_count=10, model_list_mode='reload', share=False, moderate=False, embed=False)
2024-07-03 01:39:52 | INFO | gradio_web_server | Models: ['chemvlm']
2024-07-03 01:39:52 | INFO | gradio_web_server | Namespace(host='0.0.0.0', port=10058, controller_url='http://10.140.24.69:10050', concurrency_count=10, model_list_mode='reload', share=False, moderate=False, embed=False)
2024-07-03 01:40:10 | INFO | stdout | Running on local URL:  http://0.0.0.0:10058
2024-07-03 01:40:10 | INFO | stdout | 
2024-07-03 01:40:10 | INFO | stdout | To create a public link, set `share=True` in `launch()`.
2024-07-03 15:44:59 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-07-03 15:44:59 | ERROR | stderr | Traceback (most recent call last):
2024-07-03 15:44:59 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-07-03 15:44:59 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-07-03 15:44:59 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:44:59 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-07-03 15:44:59 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-07-03 15:44:59 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:44:59 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-07-03 15:44:59 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-07-03 15:44:59 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-07-03 15:44:59 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-07-03 15:44:59 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-07-03 15:44:59 | ERROR | stderr |     raise exc
2024-07-03 15:44:59 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-07-03 15:44:59 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-07-03 15:44:59 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-07-03 15:44:59 | ERROR | stderr |     await self.app(scope, receive, send)
2024-07-03 15:44:59 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-07-03 15:44:59 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-07-03 15:44:59 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-07-03 15:44:59 | ERROR | stderr |     raise exc
2024-07-03 15:44:59 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-07-03 15:44:59 | ERROR | stderr |     await app(scope, receive, sender)
2024-07-03 15:44:59 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-07-03 15:44:59 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-07-03 15:44:59 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-07-03 15:44:59 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-07-03 15:44:59 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-07-03 15:44:59 | ERROR | stderr |     await self.app(scope, receive, send)
2024-07-03 15:44:59 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-07-03 15:44:59 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-07-03 15:44:59 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-07-03 15:44:59 | ERROR | stderr |     raise exc
2024-07-03 15:44:59 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-07-03 15:44:59 | ERROR | stderr |     await app(scope, receive, sender)
2024-07-03 15:44:59 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-07-03 15:44:59 | ERROR | stderr |     response = await func(request)
2024-07-03 15:44:59 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^
2024-07-03 15:44:59 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-07-03 15:44:59 | ERROR | stderr |     raw_response = await run_endpoint_function(
2024-07-03 15:44:59 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:44:59 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
2024-07-03 15:44:59 | ERROR | stderr |     return await run_in_threadpool(dependant.call, **values)
2024-07-03 15:44:59 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:44:59 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
2024-07-03 15:44:59 | ERROR | stderr |     return await anyio.to_thread.run_sync(func, *args)
2024-07-03 15:44:59 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:44:59 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
2024-07-03 15:44:59 | ERROR | stderr |     return await get_async_backend().run_sync_in_worker_thread(
2024-07-03 15:44:59 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:44:59 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
2024-07-03 15:44:59 | ERROR | stderr |     return await future
2024-07-03 15:44:59 | ERROR | stderr |            ^^^^^^^^^^^^
2024-07-03 15:44:59 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 859, in run
2024-07-03 15:44:59 | ERROR | stderr |     result = context.run(func, *args)
2024-07-03 15:44:59 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:44:59 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/gradio/routes.py", line 289, in api_info
2024-07-03 15:44:59 | ERROR | stderr |     return gradio.blocks.get_api_info(config, serialize)  # type: ignore
2024-07-03 15:44:59 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:44:59 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/gradio/blocks.py", line 518, in get_api_info
2024-07-03 15:44:59 | ERROR | stderr |     serializer = serializing.COMPONENT_MAPPING[type]()
2024-07-03 15:44:59 | ERROR | stderr |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
2024-07-03 15:44:59 | ERROR | stderr | KeyError: 'dataset'
2024-07-03 15:45:06 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-07-03 15:45:06 | ERROR | stderr | Traceback (most recent call last):
2024-07-03 15:45:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-07-03 15:45:06 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-07-03 15:45:06 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:45:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-07-03 15:45:06 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-07-03 15:45:06 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:45:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-07-03 15:45:06 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-07-03 15:45:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-07-03 15:45:06 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-07-03 15:45:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-07-03 15:45:06 | ERROR | stderr |     raise exc
2024-07-03 15:45:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-07-03 15:45:06 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-07-03 15:45:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-07-03 15:45:06 | ERROR | stderr |     await self.app(scope, receive, send)
2024-07-03 15:45:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-07-03 15:45:06 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-07-03 15:45:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-07-03 15:45:06 | ERROR | stderr |     raise exc
2024-07-03 15:45:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-07-03 15:45:06 | ERROR | stderr |     await app(scope, receive, sender)
2024-07-03 15:45:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-07-03 15:45:06 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-07-03 15:45:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-07-03 15:45:06 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-07-03 15:45:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-07-03 15:45:06 | ERROR | stderr |     await self.app(scope, receive, send)
2024-07-03 15:45:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-07-03 15:45:06 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-07-03 15:45:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-07-03 15:45:06 | ERROR | stderr |     raise exc
2024-07-03 15:45:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-07-03 15:45:06 | ERROR | stderr |     await app(scope, receive, sender)
2024-07-03 15:45:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-07-03 15:45:06 | ERROR | stderr |     response = await func(request)
2024-07-03 15:45:06 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^
2024-07-03 15:45:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-07-03 15:45:06 | ERROR | stderr |     raw_response = await run_endpoint_function(
2024-07-03 15:45:06 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:45:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
2024-07-03 15:45:06 | ERROR | stderr |     return await run_in_threadpool(dependant.call, **values)
2024-07-03 15:45:06 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:45:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
2024-07-03 15:45:06 | ERROR | stderr |     return await anyio.to_thread.run_sync(func, *args)
2024-07-03 15:45:06 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:45:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
2024-07-03 15:45:06 | ERROR | stderr |     return await get_async_backend().run_sync_in_worker_thread(
2024-07-03 15:45:06 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:45:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
2024-07-03 15:45:06 | ERROR | stderr |     return await future
2024-07-03 15:45:06 | ERROR | stderr |            ^^^^^^^^^^^^
2024-07-03 15:45:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 859, in run
2024-07-03 15:45:06 | ERROR | stderr |     result = context.run(func, *args)
2024-07-03 15:45:06 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:45:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/gradio/routes.py", line 289, in api_info
2024-07-03 15:45:06 | ERROR | stderr |     return gradio.blocks.get_api_info(config, serialize)  # type: ignore
2024-07-03 15:45:06 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:45:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/gradio/blocks.py", line 518, in get_api_info
2024-07-03 15:45:06 | ERROR | stderr |     serializer = serializing.COMPONENT_MAPPING[type]()
2024-07-03 15:45:06 | ERROR | stderr |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
2024-07-03 15:45:06 | ERROR | stderr | KeyError: 'dataset'
2024-07-03 15:45:09 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-07-03 15:45:09 | ERROR | stderr | Traceback (most recent call last):
2024-07-03 15:45:09 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-07-03 15:45:09 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-07-03 15:45:09 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:45:09 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-07-03 15:45:09 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-07-03 15:45:09 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:45:09 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-07-03 15:45:09 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-07-03 15:45:09 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-07-03 15:45:09 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-07-03 15:45:09 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-07-03 15:45:09 | ERROR | stderr |     raise exc
2024-07-03 15:45:09 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-07-03 15:45:09 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-07-03 15:45:09 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-07-03 15:45:09 | ERROR | stderr |     await self.app(scope, receive, send)
2024-07-03 15:45:09 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-07-03 15:45:09 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-07-03 15:45:09 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-07-03 15:45:09 | ERROR | stderr |     raise exc
2024-07-03 15:45:09 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-07-03 15:45:09 | ERROR | stderr |     await app(scope, receive, sender)
2024-07-03 15:45:09 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-07-03 15:45:10 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-07-03 15:45:10 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-07-03 15:45:10 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-07-03 15:45:10 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-07-03 15:45:10 | ERROR | stderr |     await self.app(scope, receive, send)
2024-07-03 15:45:10 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-07-03 15:45:10 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-07-03 15:45:10 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-07-03 15:45:10 | ERROR | stderr |     raise exc
2024-07-03 15:45:10 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-07-03 15:45:10 | ERROR | stderr |     await app(scope, receive, sender)
2024-07-03 15:45:10 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-07-03 15:45:10 | ERROR | stderr |     response = await func(request)
2024-07-03 15:45:10 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^
2024-07-03 15:45:10 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-07-03 15:45:10 | ERROR | stderr |     raw_response = await run_endpoint_function(
2024-07-03 15:45:10 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:45:10 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
2024-07-03 15:45:10 | ERROR | stderr |     return await run_in_threadpool(dependant.call, **values)
2024-07-03 15:45:10 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:45:10 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
2024-07-03 15:45:10 | ERROR | stderr |     return await anyio.to_thread.run_sync(func, *args)
2024-07-03 15:45:10 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:45:10 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
2024-07-03 15:45:10 | ERROR | stderr |     return await get_async_backend().run_sync_in_worker_thread(
2024-07-03 15:45:10 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:45:10 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
2024-07-03 15:45:10 | ERROR | stderr |     return await future
2024-07-03 15:45:10 | ERROR | stderr |            ^^^^^^^^^^^^
2024-07-03 15:45:10 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 859, in run
2024-07-03 15:45:10 | ERROR | stderr |     result = context.run(func, *args)
2024-07-03 15:45:10 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:45:10 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/gradio/routes.py", line 289, in api_info
2024-07-03 15:45:10 | ERROR | stderr |     return gradio.blocks.get_api_info(config, serialize)  # type: ignore
2024-07-03 15:45:10 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:45:10 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/gradio/blocks.py", line 518, in get_api_info
2024-07-03 15:45:10 | ERROR | stderr |     serializer = serializing.COMPONENT_MAPPING[type]()
2024-07-03 15:45:10 | ERROR | stderr |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
2024-07-03 15:45:10 | ERROR | stderr | KeyError: 'dataset'
2024-07-03 15:47:17 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-07-03 15:47:17 | ERROR | stderr | Traceback (most recent call last):
2024-07-03 15:47:17 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-07-03 15:47:17 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-07-03 15:47:17 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:47:17 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-07-03 15:47:17 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-07-03 15:47:17 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:47:17 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-07-03 15:47:17 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-07-03 15:47:17 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-07-03 15:47:17 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-07-03 15:47:17 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-07-03 15:47:17 | ERROR | stderr |     raise exc
2024-07-03 15:47:17 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-07-03 15:47:17 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-07-03 15:47:17 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-07-03 15:47:17 | ERROR | stderr |     await self.app(scope, receive, send)
2024-07-03 15:47:17 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-07-03 15:47:17 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-07-03 15:47:17 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-07-03 15:47:17 | ERROR | stderr |     raise exc
2024-07-03 15:47:17 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-07-03 15:47:17 | ERROR | stderr |     await app(scope, receive, sender)
2024-07-03 15:47:17 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-07-03 15:47:17 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-07-03 15:47:17 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-07-03 15:47:17 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-07-03 15:47:17 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-07-03 15:47:17 | ERROR | stderr |     await self.app(scope, receive, send)
2024-07-03 15:47:17 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-07-03 15:47:17 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-07-03 15:47:17 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-07-03 15:47:17 | ERROR | stderr |     raise exc
2024-07-03 15:47:17 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-07-03 15:47:17 | ERROR | stderr |     await app(scope, receive, sender)
2024-07-03 15:47:17 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-07-03 15:47:17 | ERROR | stderr |     response = await func(request)
2024-07-03 15:47:17 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^
2024-07-03 15:47:17 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-07-03 15:47:17 | ERROR | stderr |     raw_response = await run_endpoint_function(
2024-07-03 15:47:17 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:47:17 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
2024-07-03 15:47:17 | ERROR | stderr |     return await run_in_threadpool(dependant.call, **values)
2024-07-03 15:47:17 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:47:17 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
2024-07-03 15:47:17 | ERROR | stderr |     return await anyio.to_thread.run_sync(func, *args)
2024-07-03 15:47:17 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:47:17 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
2024-07-03 15:47:17 | ERROR | stderr |     return await get_async_backend().run_sync_in_worker_thread(
2024-07-03 15:47:17 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:47:17 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
2024-07-03 15:47:17 | ERROR | stderr |     return await future
2024-07-03 15:47:17 | ERROR | stderr |            ^^^^^^^^^^^^
2024-07-03 15:47:17 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 859, in run
2024-07-03 15:47:17 | ERROR | stderr |     result = context.run(func, *args)
2024-07-03 15:47:17 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:47:17 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/gradio/routes.py", line 289, in api_info
2024-07-03 15:47:17 | ERROR | stderr |     return gradio.blocks.get_api_info(config, serialize)  # type: ignore
2024-07-03 15:47:17 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:47:17 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/gradio/blocks.py", line 518, in get_api_info
2024-07-03 15:47:17 | ERROR | stderr |     serializer = serializing.COMPONENT_MAPPING[type]()
2024-07-03 15:47:17 | ERROR | stderr |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
2024-07-03 15:47:17 | ERROR | stderr | KeyError: 'dataset'
2024-07-03 15:47:55 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-07-03 15:47:55 | ERROR | stderr | Traceback (most recent call last):
2024-07-03 15:47:55 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-07-03 15:47:55 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-07-03 15:47:55 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:47:55 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-07-03 15:47:55 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-07-03 15:47:55 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:47:55 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-07-03 15:47:55 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-07-03 15:47:55 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-07-03 15:47:55 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-07-03 15:47:55 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-07-03 15:47:55 | ERROR | stderr |     raise exc
2024-07-03 15:47:55 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-07-03 15:47:55 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-07-03 15:47:55 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-07-03 15:47:55 | ERROR | stderr |     await self.app(scope, receive, send)
2024-07-03 15:47:55 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-07-03 15:47:55 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-07-03 15:47:55 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-07-03 15:47:55 | ERROR | stderr |     raise exc
2024-07-03 15:47:55 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-07-03 15:47:55 | ERROR | stderr |     await app(scope, receive, sender)
2024-07-03 15:47:55 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-07-03 15:47:55 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-07-03 15:47:55 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-07-03 15:47:55 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-07-03 15:47:55 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-07-03 15:47:55 | ERROR | stderr |     await self.app(scope, receive, send)
2024-07-03 15:47:55 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-07-03 15:47:55 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-07-03 15:47:55 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-07-03 15:47:55 | ERROR | stderr |     raise exc
2024-07-03 15:47:55 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-07-03 15:47:55 | ERROR | stderr |     await app(scope, receive, sender)
2024-07-03 15:47:55 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-07-03 15:47:55 | ERROR | stderr |     response = await func(request)
2024-07-03 15:47:55 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^
2024-07-03 15:47:55 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-07-03 15:47:55 | ERROR | stderr |     raw_response = await run_endpoint_function(
2024-07-03 15:47:55 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:47:55 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
2024-07-03 15:47:55 | ERROR | stderr |     return await run_in_threadpool(dependant.call, **values)
2024-07-03 15:47:55 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:47:55 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
2024-07-03 15:47:55 | ERROR | stderr |     return await anyio.to_thread.run_sync(func, *args)
2024-07-03 15:47:55 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:47:55 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
2024-07-03 15:47:55 | ERROR | stderr |     return await get_async_backend().run_sync_in_worker_thread(
2024-07-03 15:47:55 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:47:55 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
2024-07-03 15:47:55 | ERROR | stderr |     return await future
2024-07-03 15:47:55 | ERROR | stderr |            ^^^^^^^^^^^^
2024-07-03 15:47:55 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 859, in run
2024-07-03 15:47:55 | ERROR | stderr |     result = context.run(func, *args)
2024-07-03 15:47:55 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:47:55 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/gradio/routes.py", line 289, in api_info
2024-07-03 15:47:55 | ERROR | stderr |     return gradio.blocks.get_api_info(config, serialize)  # type: ignore
2024-07-03 15:47:55 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:47:55 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/gradio/blocks.py", line 518, in get_api_info
2024-07-03 15:47:55 | ERROR | stderr |     serializer = serializing.COMPONENT_MAPPING[type]()
2024-07-03 15:47:55 | ERROR | stderr |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
2024-07-03 15:47:55 | ERROR | stderr | KeyError: 'dataset'
2024-07-03 15:48:06 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-07-03 15:48:06 | ERROR | stderr | Traceback (most recent call last):
2024-07-03 15:48:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-07-03 15:48:06 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-07-03 15:48:06 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:48:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-07-03 15:48:06 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-07-03 15:48:06 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:48:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-07-03 15:48:06 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-07-03 15:48:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-07-03 15:48:06 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-07-03 15:48:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-07-03 15:48:06 | ERROR | stderr |     raise exc
2024-07-03 15:48:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-07-03 15:48:06 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-07-03 15:48:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-07-03 15:48:06 | ERROR | stderr |     await self.app(scope, receive, send)
2024-07-03 15:48:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-07-03 15:48:06 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-07-03 15:48:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-07-03 15:48:06 | ERROR | stderr |     raise exc
2024-07-03 15:48:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-07-03 15:48:06 | ERROR | stderr |     await app(scope, receive, sender)
2024-07-03 15:48:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-07-03 15:48:06 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-07-03 15:48:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-07-03 15:48:06 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-07-03 15:48:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-07-03 15:48:06 | ERROR | stderr |     await self.app(scope, receive, send)
2024-07-03 15:48:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-07-03 15:48:06 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-07-03 15:48:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-07-03 15:48:06 | ERROR | stderr |     raise exc
2024-07-03 15:48:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-07-03 15:48:06 | ERROR | stderr |     await app(scope, receive, sender)
2024-07-03 15:48:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-07-03 15:48:06 | ERROR | stderr |     response = await func(request)
2024-07-03 15:48:06 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^
2024-07-03 15:48:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-07-03 15:48:06 | ERROR | stderr |     raw_response = await run_endpoint_function(
2024-07-03 15:48:06 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:48:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
2024-07-03 15:48:06 | ERROR | stderr |     return await run_in_threadpool(dependant.call, **values)
2024-07-03 15:48:06 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:48:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
2024-07-03 15:48:06 | ERROR | stderr |     return await anyio.to_thread.run_sync(func, *args)
2024-07-03 15:48:06 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:48:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
2024-07-03 15:48:06 | ERROR | stderr |     return await get_async_backend().run_sync_in_worker_thread(
2024-07-03 15:48:06 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:48:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
2024-07-03 15:48:06 | ERROR | stderr |     return await future
2024-07-03 15:48:06 | ERROR | stderr |            ^^^^^^^^^^^^
2024-07-03 15:48:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 859, in run
2024-07-03 15:48:06 | ERROR | stderr |     result = context.run(func, *args)
2024-07-03 15:48:06 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:48:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/gradio/routes.py", line 289, in api_info
2024-07-03 15:48:06 | ERROR | stderr |     return gradio.blocks.get_api_info(config, serialize)  # type: ignore
2024-07-03 15:48:06 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:48:06 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/gradio/blocks.py", line 518, in get_api_info
2024-07-03 15:48:06 | ERROR | stderr |     serializer = serializing.COMPONENT_MAPPING[type]()
2024-07-03 15:48:06 | ERROR | stderr |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
2024-07-03 15:48:06 | ERROR | stderr | KeyError: 'dataset'
2024-07-03 15:48:21 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-07-03 15:48:21 | ERROR | stderr | Traceback (most recent call last):
2024-07-03 15:48:21 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-07-03 15:48:21 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-07-03 15:48:21 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:48:21 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-07-03 15:48:21 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-07-03 15:48:21 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:48:21 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-07-03 15:48:21 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-07-03 15:48:21 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-07-03 15:48:21 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-07-03 15:48:21 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-07-03 15:48:21 | ERROR | stderr |     raise exc
2024-07-03 15:48:21 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-07-03 15:48:21 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-07-03 15:48:21 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-07-03 15:48:21 | ERROR | stderr |     await self.app(scope, receive, send)
2024-07-03 15:48:21 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-07-03 15:48:21 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-07-03 15:48:21 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-07-03 15:48:21 | ERROR | stderr |     raise exc
2024-07-03 15:48:21 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-07-03 15:48:21 | ERROR | stderr |     await app(scope, receive, sender)
2024-07-03 15:48:21 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-07-03 15:48:21 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-07-03 15:48:21 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-07-03 15:48:21 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-07-03 15:48:21 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-07-03 15:48:21 | ERROR | stderr |     await self.app(scope, receive, send)
2024-07-03 15:48:21 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-07-03 15:48:21 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-07-03 15:48:21 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-07-03 15:48:21 | ERROR | stderr |     raise exc
2024-07-03 15:48:21 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-07-03 15:48:21 | ERROR | stderr |     await app(scope, receive, sender)
2024-07-03 15:48:21 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-07-03 15:48:21 | ERROR | stderr |     response = await func(request)
2024-07-03 15:48:21 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^
2024-07-03 15:48:21 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-07-03 15:48:21 | ERROR | stderr |     raw_response = await run_endpoint_function(
2024-07-03 15:48:21 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:48:21 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
2024-07-03 15:48:21 | ERROR | stderr |     return await run_in_threadpool(dependant.call, **values)
2024-07-03 15:48:21 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:48:21 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
2024-07-03 15:48:21 | ERROR | stderr |     return await anyio.to_thread.run_sync(func, *args)
2024-07-03 15:48:21 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:48:21 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
2024-07-03 15:48:21 | ERROR | stderr |     return await get_async_backend().run_sync_in_worker_thread(
2024-07-03 15:48:21 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:48:21 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
2024-07-03 15:48:21 | ERROR | stderr |     return await future
2024-07-03 15:48:21 | ERROR | stderr |            ^^^^^^^^^^^^
2024-07-03 15:48:21 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 859, in run
2024-07-03 15:48:21 | ERROR | stderr |     result = context.run(func, *args)
2024-07-03 15:48:21 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:48:21 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/gradio/routes.py", line 289, in api_info
2024-07-03 15:48:21 | ERROR | stderr |     return gradio.blocks.get_api_info(config, serialize)  # type: ignore
2024-07-03 15:48:21 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:48:21 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/gradio/blocks.py", line 518, in get_api_info
2024-07-03 15:48:21 | ERROR | stderr |     serializer = serializing.COMPONENT_MAPPING[type]()
2024-07-03 15:48:21 | ERROR | stderr |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
2024-07-03 15:48:21 | ERROR | stderr | KeyError: 'dataset'
2024-07-03 15:48:30 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-07-03 15:48:30 | ERROR | stderr | Traceback (most recent call last):
2024-07-03 15:48:30 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-07-03 15:48:30 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-07-03 15:48:30 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:48:30 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-07-03 15:48:30 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-07-03 15:48:30 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:48:30 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-07-03 15:48:30 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-07-03 15:48:30 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-07-03 15:48:30 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-07-03 15:48:30 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-07-03 15:48:30 | ERROR | stderr |     raise exc
2024-07-03 15:48:30 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-07-03 15:48:30 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-07-03 15:48:30 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-07-03 15:48:30 | ERROR | stderr |     await self.app(scope, receive, send)
2024-07-03 15:48:30 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-07-03 15:48:30 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-07-03 15:48:30 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-07-03 15:48:30 | ERROR | stderr |     raise exc
2024-07-03 15:48:30 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-07-03 15:48:30 | ERROR | stderr |     await app(scope, receive, sender)
2024-07-03 15:48:30 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-07-03 15:48:30 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-07-03 15:48:30 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-07-03 15:48:30 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-07-03 15:48:30 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-07-03 15:48:30 | ERROR | stderr |     await self.app(scope, receive, send)
2024-07-03 15:48:30 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-07-03 15:48:30 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-07-03 15:48:30 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-07-03 15:48:30 | ERROR | stderr |     raise exc
2024-07-03 15:48:30 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-07-03 15:48:30 | ERROR | stderr |     await app(scope, receive, sender)
2024-07-03 15:48:30 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-07-03 15:48:30 | ERROR | stderr |     response = await func(request)
2024-07-03 15:48:30 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^
2024-07-03 15:48:30 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-07-03 15:48:30 | ERROR | stderr |     raw_response = await run_endpoint_function(
2024-07-03 15:48:30 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:48:30 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
2024-07-03 15:48:30 | ERROR | stderr |     return await run_in_threadpool(dependant.call, **values)
2024-07-03 15:48:30 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:48:30 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
2024-07-03 15:48:30 | ERROR | stderr |     return await anyio.to_thread.run_sync(func, *args)
2024-07-03 15:48:30 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:48:30 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
2024-07-03 15:48:30 | ERROR | stderr |     return await get_async_backend().run_sync_in_worker_thread(
2024-07-03 15:48:30 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:48:30 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
2024-07-03 15:48:30 | ERROR | stderr |     return await future
2024-07-03 15:48:30 | ERROR | stderr |            ^^^^^^^^^^^^
2024-07-03 15:48:30 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 859, in run
2024-07-03 15:48:30 | ERROR | stderr |     result = context.run(func, *args)
2024-07-03 15:48:30 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:48:30 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/gradio/routes.py", line 289, in api_info
2024-07-03 15:48:30 | ERROR | stderr |     return gradio.blocks.get_api_info(config, serialize)  # type: ignore
2024-07-03 15:48:30 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-03 15:48:30 | ERROR | stderr |   File "/mnt/petrelfs/zhangdi1/miniforge3/envs/internvl/lib/python3.11/site-packages/gradio/blocks.py", line 518, in get_api_info
2024-07-03 15:48:30 | ERROR | stderr |     serializer = serializing.COMPONENT_MAPPING[type]()
2024-07-03 15:48:30 | ERROR | stderr |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
2024-07-03 15:48:30 | ERROR | stderr | KeyError: 'dataset'
slurmstepd: error: *** JOB 3645839 ON SH-IDC1-10-140-24-69 CANCELLED AT 2024-07-03T15:51:19 ***
